### ISSUE TITLE
新手，想请教一下如何把这个项目打包成android app？非常感谢

### ISSUE THREAD

**Issue by harlay0728** [huyanlin/news-App#3]
你好，新手想请教一下如何把这个项目打包成android app?非常感谢

**Comment by harlay0728** [comment]
问题解决了，打包成apk，调试后发现请求不到数据，报Network Error，在网上查，发现baseurl走的http，安卓9以上需要https，参考https://blog.csdn.net/qq_38904099/article/details/102959021?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~all~sobaiduend~default-2-102959021.nonecase&utm_term=%E6%89%8B%E6%9C%BAnetworkerror%E8%A7%A3%E5%86%B3&spm=1000.2123.3001.4430

**Comment by huyanlin** [comment]
请求不到数据吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huyanlin/news-App"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 晚上6:00
收件人:&nbsp;"huyanlin/news-App"<news-App@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [huyanlin/news-App] 新手，想请教一下如何把这个项目打包成android app？非常感谢 (#3)





 
问题解决了，打包成apk，调试后发现请求不到数据，报Network Error，在网上查，发现baseurl走的http，安卓9以上需要https，参考https://blog.csdn.net/qq_38904099/article/details/102959021?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~all~sobaiduend~default-2-102959021.nonecase&amp;utm_term=%E6%89%8B%E6%9C%BAnetworkerror%E8%A7%A3%E5%86%B3&amp;spm=1000.2123.3001.4430

**Comment by huyanlin** [comment]
如果您在国内，我觉得都是可以访问到的，使用cordova打包，网上都有相关教程，第一个版本很简单，没做太多。后期版本开发好了，只是没有上传




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huyanlin/news-App"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 晚上6:00
收件人:&nbsp;"huyanlin/news-App"<news-App@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [huyanlin/news-App] 新手，想请教一下如何把这个项目打包成android app？非常感谢 (#3)





 
问题解决了，打包成apk，调试后发现请求不到数据，报Network Error，在网上查，发现baseurl走的http，安卓9以上需要https，参考https://blog.csdn.net/qq_38904099/article/details/102959021?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~all~sobaiduend~default-2-102959021.nonecase&amp;utm_term=%E6%89%8B%E6%9C%BAnetworkerror%E8%A7%A3%E5%86%B3&amp;spm=1000.2123.3001.4430

**Comment by harlay0728** [comment]
> 
> 如果您在国内，我觉得都是可以访问到的，使用cordova打包，网上都有相关教程，第一个版本很简单，没做太多。后期版本开发好了，只是没有上传
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "huyanlin/news-App" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月15日(星期四) 晚上6:00 收件人:&nbsp;"huyanlin/news-App"<news-App@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [huyanlin/news-App] 新手，想请教一下如何把这个项目打包成android app？非常感谢 (#3) 问题解决了，打包成apk，调试后发现请求不到数据，报Network Error，在网上查，发现baseurl走的http，安卓9以上需要https，参考https://blog.csdn.net/qq_38904099/article/details/102959021?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~all~sobaiduend~default-2-102959021.nonecase&amp;utm_term=%E6%89%8B%E6%9C%BAnetworkerror%E8%A7%A3%E5%86%B3&amp;spm=1000.2123.3001.4430 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以访问的，是打包成apk的时候，安卓做了限制，把base url的http改成https就可以了，多谢
